version: '3'
services:
  racktables:
    image: "cent7-racktables:0.21.1"
    restart: always
    container_name: racktables
    hostname: racktables
    domainname: prosethsolutions.lab
    network_mode: bridge
    ports:
      - 8081:80
    volumes:
      - /srv/docker-data/racktables:/var/www/html
